# Generated by Django 4.2.7 on 2023-11-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papelaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtovendido',
            name='comissao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
