# Generated by Django 4.2.7 on 2023-11-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papelaria', '0002_produtovendido_comissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comissaobaseadonodia',
            name='dia_da_semana',
            field=models.CharField(choices=[('Monday', 'Segunda'), ('Tuesday', 'Terça'), ('Wednesday', 'Quarta'), ('Thursday', 'Quinta'), ('Friaday', 'Sexta'), ('Saturday', 'Sabado'), ('Sunday', 'Domingo')], max_length=100),
        ),
    ]
