# Generated by Django 4.2.7 on 2023-11-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papelaria', '0003_alter_comissaobaseadonodia_dia_da_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtovendido',
            name='comissao_configurado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
